language: java
job:
  script: mvn clean install
  script: bash <(curl -s https://detect.synopsys.com/detect.sh) --blackduck.url="https://poc70.blackduck.synopsys.com/" --blackduck.api.token="NWI1Yjc0ZmEtM2EwMi00NGZkLTgxYTktYjFmY2Q4NTkwNjU1OjU2ZWJhZGUxLTRhNGUtNDVhMi04MTJhLWRhMzY4Y2U5OWFjNQ==" --detect.project.name="wizeline-it/vulnerable-AF" --blackduck.trust.cert=true
