language: java
job:
  script: mvn clean install
  script: bash <(curl -s https://detect.synopsys.com/detect.sh) --blackduck.url="https://poc102.blackduck.synopsys.com/" --blackduck.api.token="NjE3NDkyN2QtMTkwOC00YjUzLTk0Y2QtNzE5MWE2MTExZGMzOmQ4OTQ1NzZjLWJkNTQtNDc40C1iOTM0LTNkZDE0OWI1MTMyYQ==" --detect.project.name="wizeline-it/vulnerable-AF" --blackduck.trust.cert=true
